SortBy:
  name: sortBy
  in: query
  description: Field used for sorting products.
  required: false
  schema:
    type: string
    default: createdAt
    enum:
      - id
      - name
      - sku
      - price
      - active
      - createdAt
      - updatedAt
